export default [
    {
        name: "Raccoon problem growing in Toronto",
        topic: "Raccoons",
        imageUrl: "assets/images/raccoon1.jpeg",
        contents: "The raccoons are winning. The furry masked bandits have been a problem in Toronto for years, but with COVID lockdowns and less human activity, raccoons seem to be everywhere. According to the City of Toronto, there has been a huge jump in raccoon encounters since COVID began. A March news release states that animal services saw a 300% jump in service requests for sick and injured animals last year over 2019; between January of 2020 and February of 2021, there was a 62% increase in reports of people being bitten or scratched by raccoons over previous yearly averages. The main takeaway: Stay away from raccoons and all other wildlife and do not feed the animals. Secure your garbage and don’t feed pets outside. Protect your pets. Besides a rabies vaccine, your dog needs to be vaccinated against Leptospirosis, Giardia, roundworm and canine distemper, all of which can be passed along by raccoon urine and feces. We’re getting more calls than ever before. Calls for raccoons are off the charts. Mike Heimbach, director of business development and marketing at Abell Pest Control, swears by the ounce of prevention approach. The trick with controlling wildlife around your house is to be proactive — take preventative steps before there’s a problem. Once raccoons are eating your garbage or living in your attic, it’s hard to get them to change their habits. Heimbach has seen every kind of wildlife infestation — raccoons, skunks, bats — and he feels your pain. The animals can do enormous damage to your domicile while setting up housekeeping for themselves. “We’re getting more calls than ever before,” said Heimbach in an interview Tuesday. “Calls for raccoons are off the charts.”"
    },
    {
        name: "Raccoon problem growing in Toronto",
        topic: "Raccoons",
        imageUrl: "assets/images/raccoon1.jpeg",
        contents: "The raccoons are winning. The furry masked bandits have been a problem in Toronto for years, but with COVID lockdowns and less human activity, raccoons seem to be everywhere. According to the City of Toronto, there has been a huge jump in raccoon encounters since COVID began. A March news release states that animal services saw a 300% jump in service requests for sick and injured animals last year over 2019; between January of 2020 and February of 2021, there was a 62% increase in reports of people being bitten or scratched by raccoons over previous yearly averages. The main takeaway: Stay away from raccoons and all other wildlife and do not feed the animals. Secure your garbage and don’t feed pets outside. Protect your pets. Besides a rabies vaccine, your dog needs to be vaccinated against Leptospirosis, Giardia, roundworm and canine distemper, all of which can be passed along by raccoon urine and feces. We’re getting more calls than ever before. Calls for raccoons are off the charts. Mike Heimbach, director of business development and marketing at Abell Pest Control, swears by the ounce of prevention approach. The trick with controlling wildlife around your house is to be proactive — take preventative steps before there’s a problem. Once raccoons are eating your garbage or living in your attic, it’s hard to get them to change their habits. Heimbach has seen every kind of wildlife infestation — raccoons, skunks, bats — and he feels your pain. The animals can do enormous damage to your domicile while setting up housekeeping for themselves. “We’re getting more calls than ever before,” said Heimbach in an interview Tuesday. “Calls for raccoons are off the charts.”"
    }
];