export default [
    {
        name: "Hot Spot - Selva Toronto",
        topic: "Hot spots",
        url: "hotspots.html",
        imageUrl: "assets/images/rest4.jpg",
        date: "23 November 2021",
        contents: "Selva is a glow-in-the-dark jungle-themed restaurant serving cocktails and a menu of South American eats by Chef Nuit Regular. This luminescent extravaganza, which takes over the basement of The Fifth Social Club, sits somewhere between laser tag and Rainforest Cafe. What used to be the Fifth’s unremarkable lower-level pub has been transformed by a deluge of floor-to-ceiling artwork by Clandestinos Art, comprised of husband-and-wife team Bruno Smoky and Shalak Attack. After a successful summer of technicolour patio fun at RendezViews (a collab with neighbour The Ballroom), The Fifth’s owner Oliver Gedde continues the escapist M.O. with an indoor getaway that can be visited year-round. The result is a trippy black light-lit venue complete with 3D neon-eyed aye-ayes and ayahuasca apparitions of lions and tigers. It’s certainly photogenic, but the space falls a little flat during dinner service thanks to lights that need to stay on during meal time. It's G-rated minus the immersive frills of animal sound effects and robotic hippos from childhood. Apparently Selva leans into the low-lit, cocktail atmosphere after that. I'd suggest coming then to really enjoy the artwork if it didn't mean missing out on Chef Regular’s delicious dinner dishes. The chef behind PAI, Sabai Sabai and Kiin has come up with an extensive menu that bridges some elements of Thai cuisine with South American cooking. Expect lots of limes, coconut, a signature red pepper sauce and some keto and gluten-free options (a shoutout to her husband Jeff. The ceviches ($18 each) showcase some outstanding combinations of ingredients. The version with strips of fresh young coconut incorporates red serrano chili mint and edible flowers."
    },
    {
        name: "Raccoon problem growing in Toronto",
        topic: "Raccoons",
        url: "raccoons-article.html",
        imageUrl: "assets/images/raccoon1.jpeg",
        date: "5 October 2021",
        contents: "The raccoons are winning. The furry masked bandits have been a problem in Toronto for years, but with COVID lockdowns and less human activity, raccoons seem to be everywhere. According to the City of Toronto, there has been a huge jump in raccoon encounters since COVID began. A March news release states that animal services saw a 300% jump in service requests for sick and injured animals last year over 2019; between January of 2020 and February of 2021, there was a 62% increase in reports of people being bitten or scratched by raccoons over previous yearly averages. The main takeaway: Stay away from raccoons and all other wildlife and do not feed the animals. Secure your garbage and don’t feed pets outside. Protect your pets. Besides a rabies vaccine, your dog needs to be vaccinated against Leptospirosis, Giardia, roundworm and canine distemper, all of which can be passed along by raccoon urine and feces. We’re getting more calls than ever before. Calls for raccoons are off the charts. Mike Heimbach, director of business development and marketing at Abell Pest Control, swears by the ounce of prevention approach. The trick with controlling wildlife around your house is to be proactive — take preventative steps before there’s a problem. Once raccoons are eating your garbage or living in your attic, it’s hard to get them to change their habits. Heimbach has seen every kind of wildlife infestation — raccoons, skunks, bats — and he feels your pain. The animals can do enormous damage to your domicile while setting up housekeeping for themselves. “We’re getting more calls than ever before,” said Heimbach in an interview Tuesday. “Calls for raccoons are off the charts.”"
    },
    {
        name: "Hot Spot - Selva Toronto",
        topic: "Hot spots",
        url: "hotspots.html",
        imageUrl: "assets/images/rest4.jpg",
        date: "23 November 2021",
        contents: "Selva is a glow-in-the-dark jungle-themed restaurant serving cocktails and a menu of South American eats by Chef Nuit Regular. This luminescent extravaganza, which takes over the basement of The Fifth Social Club, sits somewhere between laser tag and Rainforest Cafe. What used to be the Fifth’s unremarkable lower-level pub has been transformed by a deluge of floor-to-ceiling artwork by Clandestinos Art, comprised of husband-and-wife team Bruno Smoky and Shalak Attack. After a successful summer of technicolour patio fun at RendezViews (a collab with neighbour The Ballroom), The Fifth’s owner Oliver Gedde continues the escapist M.O. with an indoor getaway that can be visited year-round. The result is a trippy black light-lit venue complete with 3D neon-eyed aye-ayes and ayahuasca apparitions of lions and tigers. It’s certainly photogenic, but the space falls a little flat during dinner service thanks to lights that need to stay on during meal time. It's G-rated minus the immersive frills of animal sound effects and robotic hippos from childhood. Apparently Selva leans into the low-lit, cocktail atmosphere after that. I'd suggest coming then to really enjoy the artwork if it didn't mean missing out on Chef Regular’s delicious dinner dishes. The chef behind PAI, Sabai Sabai and Kiin has come up with an extensive menu that bridges some elements of Thai cuisine with South American cooking. Expect lots of limes, coconut, a signature red pepper sauce and some keto and gluten-free options (a shoutout to her husband Jeff. The ceviches ($18 each) showcase some outstanding combinations of ingredients. The version with strips of fresh young coconut incorporates red serrano chili mint and edible flowers."
    },
    {
        name: "What to eat today?",
        topic: "dine in or cook",
        url: "restaurant.html",
        imageUrl: "assets/images/raccoon1.jpeg",
        date: "5 October 2021",
        contents: "The raccoons are winning. The furry masked bandits have been a problem in Toronto for years, but with COVID lockdowns and less human activity, raccoons seem to be everywhere. According to the City of Toronto, there has been a huge jump in raccoon encounters since COVID began. A March news release states that animal services saw a 300% jump in service requests for sick and injured animals last year over 2019; between January of 2020 and February of 2021, there was a 62% increase in reports of people being bitten or scratched by raccoons over previous yearly averages. The main takeaway: Stay away from raccoons and all other wildlife and do not feed the animals. Secure your garbage and don’t feed pets outside. Protect your pets. Besides a rabies vaccine, your dog needs to be vaccinated against Leptospirosis, Giardia, roundworm and canine distemper, all of which can be passed along by raccoon urine and feces. We’re getting more calls than ever before. Calls for raccoons are off the charts. Mike Heimbach, director of business development and marketing at Abell Pest Control, swears by the ounce of prevention approach. The trick with controlling wildlife around your house is to be proactive — take preventative steps before there’s a problem. Once raccoons are eating your garbage or living in your attic, it’s hard to get them to change their habits. Heimbach has seen every kind of wildlife infestation — raccoons, skunks, bats — and he feels your pain. The animals can do enormous damage to your domicile while setting up housekeeping for themselves. “We’re getting more calls than ever before,” said Heimbach in an interview Tuesday. “Calls for raccoons are off the charts.”"
    }
];